name: CI

on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v1"

      - uses: php-actions/composer@v1
      - uses: php-actions/phpunit@v1

      - name: "Run tests with phpunit/phpunit"
        run: "include/vendor/bin/phpunit --testdox tests"